[package]
name = "mizer-debug-ui"
version = "0.1.0"
authors = ["Max JÃ¶hnk <maxjoehnk@gmail.com>"]
edition = "2021"

[dependencies]
anyhow = "1"
tracing = "0.1"
profiling = "1"
futures = { version = "0.3", features = ["executor"] }
mizer-injector = { path = "../injector" }
