[package]
name = "mizer-status-bus"
version = "0.1.0"
authors = ["Max JÃ¶hnk <maxjoehnk@gmail.com>"]
edition = "2021"

[dependencies]
anyhow = "1"
log = "0.4"
mizer-message-bus = { path = "../../util/bus" }
chrono = { version = "0.4", features = ["serde"] }
serde = { version = "1", features = ["derive"] }
