[package]
name = "mizer-timing-nodes"
version = "0.1.0"
authors = ["Max JÃ¶hnk <maxjoehnk@gmail.com>"]
edition = "2021"

[dependencies]
anyhow = "1.0.82"
mizer-node = { path = "../../../node" }
mizer-clock = { path = "../../../../clock" }
serde = { version = "1", features = ["derive"] }
cron = "0.12"
chrono = "0.4"
