[package]
name = "mizer-node-ports"
version = "0.1.0"
authors = ["Max JÃ¶hnk <maxjoehnk@gmail.com>"]
edition = "2018"

[dependencies]
anyhow = "1"
crossbeam = "0.8"
serde = { version = "1", features = ["derive"] }
bincode = "1.3"
