[package]
name = "mizer-surfaces"
version = "0.1.0"
authors = ["Max JÃ¶hnk <maxjoehnk@gmail.com>"]
edition = "2021"

[dependencies]
anyhow = "1"
serde = { version = "1", features = ["derive"] }
mizer-module = { path = "../../runtime/module" }
mizer-message-bus = { path = "../../util/bus" }
mizer-commander = { path = "../../runtime/commander" }
pinboard = "2.2"
profiling = "1"
dashmap = "5"
uuid = { version = "1.7", features = ["v4", "serde"] }
tracing = "0.1"
