[package]
name = "mizer-midi-nodes"
version = "0.1.0"
authors = ["Max JÃ¶hnk <maxjoehnk@gmail.com>"]
edition = "2018"

[dependencies]
log = "0.4"
anyhow = "1"
serde = { version = "1", features = ["derive"] }
mizer-node = { path = "../../../../node" }
mizer-protocol-midi = { path = "../../../../../../components/connections/protocols/midi" }
mizer-util = { path = "../../../../../../util" }
mizer-message-bus = { path = "../../../../../../util/bus" }
