[package]
name = "mizer-midi-device-profiles"
version = "0.1.0"
authors = ["Max JÃ¶hnk <maxjoehnk@gmail.com>"]
edition = "2021"

[dependencies]
tracing = "0.1"
anyhow = "1"
serde = { version = "1", features = ["derive"] }
serde_yaml = "0.8"
rhai = { version = "1.17", features = ["sync"] }
mizer-midi-messages = { path = "../messages" }
mizer-util = { path = "../../../../../util" }
