[package]
name = "mizer-mqtt-nodes"
version = "0.1.0"
authors = ["Max JÃ¶hnk <maxjoehnk@gmail.com>"]
edition = "2021"

[dependencies]
anyhow = "1"
serde = { version = "1", features = ["derive"] }
mizer-node = { path = "../../../../node" }
mizer-protocol-mqtt = { path = "../../../../../../components/connections/protocols/mqtt" }
mizer-util = { path = "../../../../../../util" }
