[package]
name = "mizer-protocol-citp"
version = "0.1.0"
authors = ["Max JÃ¶hnk <maxjoehnk@gmail.com>"]
edition = "2021"

[dependencies]
anyhow = "1"
mizer-processing = { path = "../../../../runtime/processing" }
mizer-module = { path = "../../../../runtime/module" }
mizer-commander = { path = "../../../../runtime/commander" }
mizer-status-bus = { path = "../../../../runtime/status" }
profiling = "1"
tracing = "0.1"
citp = "0.2"
mizer-fixtures = { path = "../../../fixtures" }
tokio = { version = "1", features = ["net"] }
uuid = "1.7"
flume = "0.11"
async-stream = "0.3"
futures = "0.3"
