[package]
name = "mizer-laser-nodes"
version = "0.1.0"
authors = ["Max JÃ¶hnk <maxjoehnk@gmail.com>"]
edition = "2018"

[dependencies]
anyhow = "1"
log = "0.4"
mizer-node-api = { path = "../api" }
mizer-protocol-laser = { path = "../../protocols/laser" }
mizer-devices = { path = "../../devices" }
