[package]
name = "mizer-midi-nodes"
version = "0.1.0"
authors = ["Max JÃ¶hnk <maxjoehnk@gmail.com>"]
edition = "2021"

[dependencies]
tracing = "0.1"
anyhow = "1"
serde = { version = "1", features = ["derive"] }
mizer-node = { path = "../../../../node" }
mizer-protocol-midi = { path = "../../../../../../components/connections/protocols/midi" }
mizer-util = { path = "../../../../../../util" }
mizer-message-bus = { path = "../../../../../../util/bus" }
enum-iterator = "2.0"
num_enum = "0.7.2"
