[package]
name = "mizer-text-nodes"
version = "0.1.0"
authors = ["Max JÃ¶hnk <maxjoehnk@gmail.com>"]
edition = "2021"

[dependencies]
anyhow = "1.0.82"
tracing = "0.1"
mizer-node = { path = "../../../node" }
serde = { version = "1", features = ["derive"] }
enum-iterator = "2.0"
num_enum = "0.7"
mizer-wgpu = { path = "../../../../wgpu" }
image = "0.24"
profiling = "1"
glyphon = "0.5.0"
font-kit = "0.13"
