[package]
name = "mizer-node"
version = "0.1.0"
authors = ["Max JÃ¶hnk <maxjoehnk@gmail.com>"]
edition = "2021"

[features]
test = []

[dependencies]
anyhow = "1"
log = "0.4"
serde = { version = "1", features = ["derive"] }
mizer-clock = { path = "../../clock" }
mizer-ports = { path = "../ports" }
mizer-injector = { path = "../../injector" }
downcast = "0.11"

[dev-dependencies]
test-case = "2.2"
