[package]
name = "mizer-devices"
version = "0.1.0"
authors = ["Max JÃ¶hnk <maxjoehnk@gmail.com>"]
edition = "2021"

[dependencies]
anyhow = "1"
dashmap = "5"
tracing = "0.1"
mizer-protocol-laser = { path = "../protocols/laser" }
mizer-gamepads = { path = "./gamepads" }
mizer-g13 = { path = "./g13" }
mizer-webcams = { path = "./webcams" }
mizer-ndi = { path = "./ndi" }
mizer-module = { path = "../../../runtime/module" }
mizer-processing = { path = "../../../runtime/processing" }
mizer-protocol-pro-dj-link = { path = "../protocols/pro-dj-link" }
tokio = { version = "1.37", features = ["sync", "rt"] }
tokio-stream = "0.1"
futures = "0.3"
derive_more = "0.99.17"
profiling = "1.0"
