[package]
name = "mizer-connections"
version = "0.1.0"
authors = ["Max JÃ¶hnk <maxjoehnk@gmail.com>"]
edition = "2021"

[dependencies]
anyhow = "1"
log = "0.4"
dashmap = "5"
derive_more = "0.99"
mizer-protocol-citp = { path = "./protocols/citp" }
mizer-protocol-dmx = { path = "./protocols/dmx" }
mizer-protocol-midi = { path = "./protocols/midi" }
mizer-protocol-osc = { path = "./protocols/osc" }
mizer-protocol-pro-dj-link = { path = "./protocols/pro-dj-link" }
mizer-devices = { path = "./devices" }
