[package]
name = "mizer-settings"
version = "0.1.0"
authors = ["Max JÃ¶hnk <maxjoehnk@gmail.com>"]
edition = "2021"

[dependencies]
anyhow = "1"
tracing = "0.1"
serde = { version = "1", features = ["derive"] }
toml = "0.9"
directories-next = "2.0"
enum-iterator = "2.0"
facet = { version = "0.43", features = ["reflect"] }
heck = "0.5"
itertools = "0.14"
