[general]
language = "en"
auto_load_last_project = true

[paths]
midi_device_profiles = "crates/components/connections/protocols/midi/device-profiles/profiles"
media_storage = ".storage"

[paths.fixture_libraries]
open_fixture_library = "crates/components/fixtures/open-fixture-library/.fixtures"
qlcplus = "crates/components/fixtures/qlcplus/.fixtures"
gdtf = "crates/components/fixtures/gdtf/.fixtures"
mizer = "crates/components/fixtures/mizer-definitions/.fixtures"

[hotkeys.global]
layout_view = "f1"
plan_view = "f2"
previz_view = "f3"
nodes_view = "f4"
sequencer_view = "f5"
programmer_view = "f6"
presets_view = "f7"
effects_view = "f8"
media_view = "f9"
surfaces_view = "f10"
connections_view = "f11"
fixture_patch_view = "f12"
programmer_pane = "shift+p"
selection_pane = "shift+s"
undo = "ctrl+z"
redo = "ctrl+shift+z"
open = "ctrl+o"
save = "ctrl+s"
save_as = "ctrl+shift+s"

[hotkeys.layouts]
add_layout = "alt+a"

[hotkeys.plan]
store = "insert"
highlight = "home"
clear = "backspace"

[hotkeys.programmer]
select_all = "ctrl+a"
clear = "backspace"
store = "insert"
highlight = "home"
assign_group = "ctrl+g"
next = "right"
prev = "left"
shuffle = "ctrl+r"

[hotkeys.patch]
add_fixture = "alt+a"
select_all = "ctrl+a"
clear = "backspace"
delete = "delete"
assign_group = "ctrl+g"

[hotkeys.nodes]
add_node = "alt+a"
duplicate_node = "ctrl+d"
group_nodes = "ctrl+g"
delete_node = "delete"
rename_node = "ctrl+r"

[hotkeys.sequencer]
add_sequence = "alt+a"
delete = "delete"
duplicate = "ctrl+d"
go_forward = "ctrl+g"

[hotkeys.effects]
delete = "delete"
add_effect = "alt+a"
