[package]
name = "mizer-clock-nodes"
version = "0.1.0"
authors = ["Max JÃ¶hnk <maxjoehnk@gmail.com>"]
edition = "2021"

[dependencies]
anyhow = "1"
serde = { version = "1", features = ["derive"] }
mizer-clock = { path = "../../../clock" }
mizer-node = { path = "../../node" }
chrono = "0.4"