[package]
name = "mizer-pipeline"
version = "0.1.0"
authors = ["Max JÃ¶hnk <maxjoehnk@gmail.com>"]
edition = "2021"

[dependencies]
anyhow = "1"
metrics = "0.22.3"
mizer-debug-ui-impl = { path = "../debug-ui/impl" }
mizer-fixtures = { path = "../../components/fixtures" }
mizer-protocol-laser = { path = "../../components/connections/protocols/laser" }
mizer-project-files = { path = "../../projects" }
mizer-devices = { path = "../../components/connections/devices" }
mizer-node = { path = "node" }
mizer-nodes = { path = "nodes" }
mizer-video-nodes = { path = "nodes/video" }
mizer-clock = { path = "../clock" }
mizer-ports = { path = "ports" }
mizer-processing = { path = "../processing" }
mizer-util = { path = "../../util" }
mizer-wgpu = { path = "../wgpu" }
dashmap = "5"
flume = "0.11"
ringbuffer = "0.15"
downcast = "0.11"
profiling = "1"
pinboard = "2.2"
tracing = "0.1"
tracing-unwrap = "1.0"
parking_lot = "0.12"

[dev-dependencies]
test-case = "3.3"
