[package]
name = "mizer-sequencer-commands"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1"
serde = { version = "1", features = ["derive"] }
mizer-commander = { path = "../../../runtime/commander" }
mizer-node = { path = "../../../runtime/pipeline/node" }
mizer-nodes = { path = "../../../runtime/pipeline/nodes" }
mizer-runtime = { path = "../../../runtime" }
mizer-layouts = { path = "../../../runtime/layouts" }
mizer-sequencer = { path = ".." }
mizer-fixtures = { path = "../../fixtures" }
mizer-node-ports = { path = "../../ports" }
