[package]
name = "mizer-osc-nodes"
version = "0.1.0"
authors = ["Max JÃ¶hnk <maxjoehnk@gmail.com>"]
edition = "2018"

[dependencies]
anyhow = "1"
serde = { version = "1", features = ["derive"] }
mizer-node = { path = "../../../node" }
rosc = "0.4"
crossbeam-channel = "0.4"
lazy_static = "1.4"
log = "0.4"
