[package]
name = "mizer-nodes"
version = "0.1.0"
authors = ["Max JÃ¶hnk <maxjoehnk@gmail.com>"]
edition = "2021"

[dependencies]
anyhow = "1"
log = "0.4"
serde = { version = "1", features = ["derive", "rc"] }
mizer-node = { path = "../node" }
mizer-clock-nodes = { path = "clock" }
mizer-color-nodes = { path = "behaviors/color" }
mizer-conversion-nodes = { path = "behaviors/conversions" }
mizer-envelope-nodes = { path = "behaviors/envelope" }
mizer-oscillator-nodes = { path = "behaviors/oscillator" }
mizer-port-operation-nodes = { path = "behaviors/port-operations" }
mizer-dmx-nodes = { path = "connections/protocols/dmx" }
mizer-gamepad-nodes = { path = "connections/gamepad" }
mizer-scripting-nodes = { path = "behaviors/scripting" }
mizer-sequence-nodes = { path = "behaviors/sequence" }
mizer-math-nodes = { path = "behaviors/math" }
mizer-sequencer-nodes = { path = "sequencer" }
mizer-fixture-nodes = { path = "fixture" }
mizer-laser-nodes = { path = "connections/laser" }
mizer-input-nodes = { path = "inputs" }
mizer-midi-nodes = { path = "connections/protocols/midi" }
mizer-mqtt-nodes = { path = "connections/protocols/mqtt" }
mizer-pixel-nodes = { path = "pixels" }
mizer-opc-nodes = { path = "connections/protocols/opc" }
mizer-osc-nodes = { path = "connections/protocols/osc" }
mizer-video-nodes = { path = "video" }
mizer-data-nodes = { path = "data" }
mizer-plan-nodes = { path = "plan" }
mizer-timing-nodes = { path = "behaviors/timing" }
derive_more = "0.99"

[dev-dependencies]
mizer-node = { path = "../node", features = ["test"] }
mizer-util = { path = "../../../util", features = ["test"] }
test-case = "2.2"
insta = "1.23"
plotters = { version = "0.3", default-features = false, features = ["svg_backend", "area_series"] }
