[package]
name = "mizer-ui-api"
version = "0.1.0"
authors = ["Max JÃ¶hnk <maxjoehnk@gmail.com>"]
edition = "2021"

[dependencies]
anyhow = "1"
mizer-module = { path = "../../runtime/module" }
profiling = "1"
tracing = "0.1"
futures = "0.3"
mizer-message-bus = { path = "../../util/bus" }
flume = "0.11"