[package]
name = "mizer-port-operation-nodes"
version = "0.1.0"
authors = ["Max JÃ¶hnk <maxjoehnk@gmail.com>"]
edition = "2021"

[dependencies]
anyhow = "1"
tracing = "0.1"
mizer-node = { path = "../../../node" }
serde = { version = "1", features = ["derive"] }
itertools = "0.12.1"
rand = "0.8"
mizer-util = { path = "../../../../../util" }
enum-iterator = "2.0"
num_enum = "0.7"
mizer-wgpu = { path = "../../../../wgpu" }
mizer-protocol-laser = { path = "../../../../../components/connections/protocols/laser" }

[dev-dependencies]
test-case = "3.3"
