[general]
language = "en"

[paths]
midi_device_profiles = "components/connections/protocols/midi/device-profiles/profiles"

[paths.fixture_libraries]
open_fixture_library = "components/fixtures/open-fixture-library/.fixtures"
qlcplus = "components/fixtures/qlcplus/.fixtures"
gdtf = "components/fixtures/gdtf/.fixtures"

[hotkeys.global]
layout_view = "f1"
plan_view = "f2"
previz_view = "f3"
nodes_view = "f4"
sequencer_view = "f5"
programmer_view = "f6"
presets_view = "f7"
effects_view = "f8"
media_view = "f9"
surfaces_view = "f10"
connections_view = "f11"
fixture_patch_view = "f12"
undo = "ctrl+z"
redo = "ctrl+shift+z"

[hotkeys.layouts]
add_layout = "alt+a"

[hotkeys.plan]
store = "insert"
highlight = "home"
clear = "backspace"

[hotkeys.programmer]
select_all = "ctrl+a"
clear = "backspace"
store = "insert"
highlight = "home"

[hotkeys.patch]
add_fixture = "alt+a"
select_all = "ctrl+a"
clear = "backspace"
delete = "delete"
assign_group = "ctrl+g"

[hotkeys.nodes]
add_node = "alt+a"
duplicate_node = "ctrl+d"

[hotkeys.sequencer]
add_sequence = "alt+a"
delete = "delete"
