[package]
name = "mizer-pixel-nodes"
version = "0.1.0"
authors = ["Max JÃ¶hnk <maxjoehnk@gmail.com>"]
edition = "2021"

[dependencies]
anyhow = "1"
mizer-node = { path = "../../node" }
serde = { version = "1", features = ["derive"] }
mizer-protocol-dmx = { path = "../../../../components/connections/protocols/dmx" }
mizer-util = { path = "../../../../util" }
test-case = "3.3"
enum-iterator = "2.0"
num_enum = "0.7.2"
tracing = "0.1"
image = "0.24"
mizer-wgpu = { path = "../../../wgpu" }
