[package]
name = "mizer-protocol-midi"
version = "0.1.0"
authors = ["Max JÃ¶hnk <maxjoehnk@gmail.com>"]
edition = "2021"

[dependencies]
anyhow = "1"
midir = "0.10"
dashmap = "5"
mizer-console = { path = "../../../console" }
mizer-processing = { path = "../../../../runtime/processing" }
mizer-module = { path = "../../../../runtime/module" }
mizer-midi-device-profiles = { path = "device-profiles" }
mizer-util = { path = "../../../../util" }
mizer-message-bus = { path = "../../../../util/bus" }
mizer-midi-messages = { path = "messages" }
regex = "1.10"
lazy_static = "1.4"
profiling = "1"
tracing = "0.1"
parking_lot = "0.12.2"
