[package]
name = "mizer-debug-ui-egui"
version = "0.1.0"
authors = ["Max JÃ¶hnk <maxjoehnk@gmail.com>"]
edition = "2021"

[dependencies]
anyhow = "1"
egui = "0.23"
egui-winit = "0.23"
egui-wgpu = { version = "0.23", features = ["winit"] }
winit = "0.28"
image = "0.24"
log = "0.4"
profiling = "1"
futures = { version = "0.3", features = ["executor"] }
mizer-wgpu = { path = "../../wgpu" }
mizer-debug-ui = { path = ".." }
mizer-module = { path = "../../module" }
