[package]
name = "mizer-ndi"
version = "0.1.0"
authors = ["Max JÃ¶hnk <maxjoehnk@gmail.com>"]
edition = "2021"

[dependencies]
tracing = "0.1"
anyhow = "1"
futures = "0.3.30"
flume = "0.11"
pinboard = "2.2"
enum-iterator = "2.0"
ndi = { git = "https://github.com/maxjoehnk/ndi-rs.git", branch = "feature/ndi-5" }
image = "0.24"
