[package]
name = "mizer-command-executor"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1"
log = "0.4"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
derive_more = "0.99"
mizer-commander = { path = ".." }
mizer-processing = { path = "../../processing" }
mizer-module = { path = "../../module" }
mizer-runtime = { path = "../.." }
mizer-fixture-commands = { path = "../../../components/fixtures/commands" }
mizer-sequencer-commands = { path = "../../../components/sequencer/commands" }
mizer-timecode = { path = "../../../components/timecode" }
mizer-plan = { path = "../../../components/plan" }
mizer-layouts = { path = "../../layouts" }
mizer-layout-commands = { path = "../../layouts/commands" }
mizer-node = { path = "../../pipeline/node" }
mizer-protocol-dmx = { path  = "../../../components/connections/protocols/dmx" }
mizer-protocol-mqtt = { path  = "../../../components/connections/protocols/mqtt" }
mizer-protocol-osc = { path  = "../../../components/connections/protocols/osc" }
mizer-node-templates = { path = "../../pipeline/templates" }
mizer-surfaces = { path = "../../../components/surfaces" }
flume = "0.11"
tracing = "0.1"
