[package]
name = "mizer-g13"
version = "0.1.0"
authors = ["Max JÃ¶hnk <maxjoehnk@gmail.com>"]
edition = "2021"

[dependencies]
tracing = "0.1"
anyhow = "1"
g13 = "0.1"
flume = "0.11"
pinboard = "2.2"
uuid = { version = "1.8", features = ["v4"] }
rusb = "*"
mizer-module = { path = "../../../../runtime/module" }
mizer-connection-contracts = { path = "../../contracts" }
