[package]
name = "mizer-gamepads"
version = "0.1.0"
authors = ["Max JÃ¶hnk <maxjoehnk@gmail.com>"]
edition = "2021"

[dependencies]
tracing = "0.1"
anyhow = "1"
gilrs = "0.11"
futures = "0.3"
flume = "0.11"
pinboard = "2.2"
enum-iterator = "2.0"
mizer-console = { path = "../../../console" }
mizer-module = { path = "../../../../runtime/module" }
mizer-connection-contracts = { path = "../../contracts" }
