[package]
name = "mizer-osc-nodes"
version = "0.1.0"
authors = ["Max JÃ¶hnk <maxjoehnk@gmail.com>"]
edition = "2021"

[dependencies]
anyhow = "1"
serde = { version = "1", features = ["derive"] }
mizer-node = { path = "../../../../node" }
mizer-connections = { path = "../../../../../../components/connections" }
tracing = "0.1"
mizer-util = { path = "../../../../../../util" }
enum-iterator = "2.0"
num_enum = "0.7"
