[package]
name = "mizer-gamepad-nodes"
version = "0.1.0"
authors = ["Max JÃ¶hnk <maxjoehnk@gmail.com>"]
edition = "2021"

[dependencies]
anyhow = "1"
tracing = "0.1"
serde = { version = "1", features = ["derive"] }
mizer-gamepads = { path = "../../../../../components/connections/devices/gamepads" }
mizer-connections = { path = "../../../../../components/connections" }
mizer-node = { path = "../../../node" }
mizer-util = { path = "../../../../../util" }
enum-iterator = "2.0"
num_enum = "0.7"
