[package]
name = "mizer-docs"
version = "0.1.0"
authors = ["Max JÃ¶hnk <maxjoehnk@gmail.com>"]
edition = "2021"

[dependencies]
phf = "0.11"
heck = "0.5"

[build-dependencies]
anyhow = "1"
phf_codegen = "0.11"
