name: mizer
description: UI for Mizer
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.14.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  i18n_extension: ^4.2.1
  protobuf: ^2.0.0
  grpc: ^3.0.0
  fixnum: ^1.0.0
  bloc: ^7.2.1
  flutter_bloc: ^7.3.0
  provider: ^6.0.0
  material_design_icons_flutter: ^5.0.5955-rc.1
  file_selector: ^0.8.2
  file_selector_linux: ^0.0.2
  file_selector_macos: ^0.0.4
  multicast_dns: ^0.3.1
  select_form_field: ^2.2.0
  collection: ^1.15.0
  nativeshell: ^0.1.13
  flutter_svg: ^1.0.0
  flex_color_picker: ^2.1.2
  keyboard_shortcuts:
    git:
      url: https://github.com/rlch/keyboard_shortcuts.git
      ref: e33efe2
  auto_size_text: ^3.0.0
  from_css_color: ^2.0.0
  ffi: ^1.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  test: ^1.17.0
  mockito: ^5.0.0
  bloc_test: ^8.2.0
  ffigen: ^4.1.2
  widgetbook: ^2.0.9
  flutter_launcher_icons: ^0.9.2

flutter:
  uses-material-design: true
  assets:
    - assets/icons/
    - assets/locales/

ffigen:
  output: 'lib/api/plugin/ffi/bindings.dart'
  name: 'FFIBindings'
  headers:
    entry-points:
      - 'ffi.h'
    include-directives:
      - 'ffi.h'

flutter_icons:
  image_path: ../assets/logo@512.png
  android: true
  ios: true
