[package]
name = "mizer-opc-nodes"
version = "0.1.0"
authors = ["Max JÃ¶hnk <maxjoehnk@gmail.com>"]
edition = "2018"

[dependencies]
anyhow = "1"
serde = { version = "1", features = ["derive"] }
mizer-util = { path = "../../../../../../util" }
mizer-node = { path = "../../../../node" }
log = "0.4"
bytes = "0.5"
