[package]
name = "mizer-module"
version = "0.1.0"
authors = ["Max JÃ¶hnk <maxjoehnk@gmail.com>"]
edition = "2021"

[dependencies]
anyhow = "1.0.82"
mizer-processing = { path = "../processing" }
tracing = "0.1"
mizer-settings = { path = "../settings"}
mizer-status-bus = { path = "../../runtime/status" }

[dev-dependencies]
test-case = "3.3"
