[package]
name = "mizer-wgpu"
version = "0.1.0"
authors = ["Max JÃ¶hnk <maxjoehnk@gmail.com>"]
edition = "2021"

[dependencies]
wgpu = { version = "0.20", features = ["trace"] }
anyhow = "1"
winit = { version = "0.29", features = ["rwh_05"] }
bytemuck = { version = "1.15", features = ["derive"] }
raw-window-handle = "0.5"
tracing = "0.1"
uuid = { version = "1.8", features = ["v4"] }
image = "0.25"
mizer-module = { path = "../module" }
profiling = "1"
dashmap = "6.0"
weak-table = "0.3"
parking_lot = "0.12"
